default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PW'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: CapstoneModuleOne_development
  
test:
  <<: *default
  database: CapstoneModuleOne_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
